#!/bin/bash

#variables

DBUSER=root
FMTOPTIONS='--skip-colum-names -E'
COMMAND='SHOW DATABASES'
BACKUPDIR=/dbbackup

#backup non-system databases

for DBNAME in $(mysql $FMOPTIONS -u $DBUSER -e "$COMMAND" | grep -v ^* | grep -v information_schema | grep -v performance_schema); do 
echo "BACKING UP \"$DBNAME\""
mysqldump -u $DBUSER $DBNAME > $BACKUPDIR/$DBNAME.dump
done

#add up size of all database dumps

for DBDUMP in $BACKUPDIR/*; do
SIZE=$(stat --printf "%s\n" $DBDUMP)
TOTAL=$(( $TOTAL + $SIZE ))
done

# REPORT NAME, Size, and percentage of total for each database dump

echo
for DBDUMP in $BACKUIPDIR/*; do
SIZE=$(stat --printf ""%s\n" $DBDUMP)
echo "$DBDUMP,$SIZE,$(( 100 * $SIZE / $TOTAL ))%"
done
