#!/bin/bash

#this is for cron to check for watering times
#my tent hours are are coded in py script

cd /home/pi/Desktop/Watering_project/scripts
python3 timer_water.py >> /home/pi/Desktop/Watering_project/Data/water_log.txt
